name: PackageVersionRelease
on:
  push:
    paths:
      - bla.txt
jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get -y install zip

      - name: Package bla.txt
        run: |
          wget -O wiki.txt https://en.wikipedia.org/wiki/Special:Random
          zip bla.zip *.txt

      - name: Bump version number
        run: |
          version=$(grep -m 1 'version' app-info.yaml | awk '{print $2}')
          echo $version
          major=$(echo $version | cut -d'.' -f1)
          minor=$(echo $version | cut -d'.' -f2)
          patch=$(echo $version | cut -d'.' -f3)
          new_minor=$(expr $minor + 1)
          echo "NEW_VERSION=$major.$new_minor.$patch" >> $GITHUB_ENV
          echo ${{ env.NEW_VERSION }}
          sed -i "s/version: $version/version: ${{ env.NEW_VERSION }}/g" app-info.yaml

      - name: Push version file to master
        run: |
          git config user.name "itaynvn"
          git config user.email "itay.anavian@cnvrg.io"
          git add app-info.yaml
          git commit -m "Version bump to ${{ env.NEW_VERSION }}"
          git push origin HEAD:main
        with:
          publish_dir: ./
          github_token: ${{ secrets.ACCESS_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename zip file with new version
        run: |
          echo ${{ env.NEW_VERSION }}
          mv bla.zip ${{ env.NEW_VERSION }}.zip
          ls -la *.zip

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          github_token: ${{ secrets.ACCESS_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Release ${{ env.NEW_VERSION }}
          draft: false
          prerelease: false
